### ISSUE TITLE
Have you looked into using Scuttlebutt or Gun for underlying database?

### ISSUE THREAD

**Issue by timjrobinson** [deepvalue-network/software#3]
It looks like you're building the blockchain and connection system from scratch for this project. It'd save you a lot of time to use something that's already available and build the tools you want on top of it. 

A similar project is [Scuttlebutt](https://scuttlebutt.nz) which is a peer to peer social network. You can easily change the secret handshake key to something random to create your own network separate just for this project. This seems very similar to what you're building and has been ongoing for 5+ years so most of the hard problems you're solving are already solved. They also have a [Go client](https://github.com/cryptoscope/ssb) if you're a big fan of Go. 

There's also [Gun](https://gun.eco) which is a decentralized database. I haven't used this as much but it could be another good alternative.

**Comment by steve-rodrigue** [comment]
Hi there.

Scuttlebutt is a decentralized social network software.  It is not suitable to build the whole ecosystem we want to build.  Gun uses a data sharing and a concensus mechanism where all data is shared with everyone.  In a decentralized environment, not all data should be shared with everyone.

On top of that, our solution will make it easy to separate the query, communication, disk and engine layers.  This will enable people to bind together the components they need in their project and connect them using the logic they want.  If that logic changes over time, the developer of their project will be able to achieve a concensus and update their logic the way they see fit.

I also analyzed BigChainDB before working on this project.  None of the existing projects were suitable for what we are building.

Thanks,
Steve
